# Generated by Django 6.0.2 on 2026-03-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphQL", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
