# Generated by Django 6.0.2 on 2026-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphQL", "0002_blog_deleted_at_blog_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blogtag",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
